[build]
  command = "npm run build"
  # 👇 check your dist folder after build
 dist/AnuRagProTfoLio/browser/index.html


[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
