[build]
  command = "npm run build"
  # 👇 check your dist folder after build
 publish = "dist/AnuRagProTfoLio"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
